/**
 * This file is generated. Do not modify this file.
 * It was generated at build time of the app, via pnpm dev or pnpm build.
 * It was generated by the file /Users/jamie/Code/hex-digital/hex-internal/projects/lucidity/lucidity-next-sanity-starter/apps/sanity/features/modular-content-blocks/scripts/generate-sanity-block-schema-imports.cjs.
 * It was last generated at Tue, 14 Jan 2025 22:45:50 GMT.
 */

import { schema as outerSchema0 } from './../blocks/outer/Section/schema';
import { schema as innerSchema0 } from './../blocks/inner/RawHtml/schema';

export const outerBlocksSchema = [{ schema: outerSchema0 }];

export const innerBlocksSchema = [{ schema: innerSchema0 }];
